/**
 * Generates the palette stylesheets from `scripts/palettes.ts`.
 *
 * Output goes to `src/themes/`, which contains generated CSS and nothing else —
 * tsdown copies that directory verbatim into `dist/themes/`.
 *
 * Two forms per palette, from one set of values so they cannot drift:
 *   <name>.css          `:root` + `.dark`
 *   <name>.scoped.css   `[data-palette="<name>"]` + `.dark[data-palette=...]`
 *
 * Each dark or scoped selector also matches the marker ThemeProvider puts in
 * <body> before React hydrates (see theme-provider.tsx), with the same
 * specificity, so the palette is right from the first paint.
 *
 * Run via `bun run themes`, which `bun run build` does before tsdown so the
 * files exist for the `copy` step and for publint's export validation.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { type Palette, PALETTE_TOKENS, PALETTES } from "./palettes.ts";

const THEMES_DIR = join(import.meta.dirname, "..", "src", "themes");

function declarations(
  values: Record<string, string>,
  extra?: Record<string, string>,
): string {
  const lines = Object.entries(extra ?? {}).map(
    ([token, value]) => `  --${token}: ${value};`,
  );

  for (const token of PALETTE_TOKENS) {
    lines.push(`  --${token}: ${values[token]};`);
  }

  return lines.join("\n");
}

function header(name: string, palette: Palette, scoped: boolean): string {
  return `/**
 * ${palette.label} — ${palette.description}
 *
 * GENERATED by scripts/build-themes.ts from scripts/palettes.ts.
 * Do not edit; your changes will be overwritten on the next build.
 *
 * Usage:
 *
 *   @import "tailwindcss";
 *   @import "xiod-ui/styles";
 *   @import "xiod-ui/themes/${name}${scoped ? "/scoped" : ""}";
 *${
   scoped
     ? `
 * Applies only where \`data-palette="${name}"\` is set. Use this form when your
 * app switches palettes at runtime — pass \`defaultPalette\` to ThemeProvider
 * and call \`setPalette("${name}")\` from \`useTheme()\`. For a single fixed
 * palette import "xiod-ui/themes/${name}" instead, which needs no attribute.`
     : `
 * Overrides the base tokens directly, so no attribute on \`<html>\` is needed.
 * Your own \`:root\` block placed after this import still wins — same
 * specificity, later in source order.`
 }
 */`;
}

/** Matches `:root` while ThemeProvider's pre-hydration marker carries these classes. */
function marker(classes: string): string {
  return `:where(:has(> body > ${classes}))`;
}

function render(name: string, palette: Palette, scoped: boolean): string {
  // Pairs of selectors with equal specificity: the attribute form on <html>,
  // and the pre-hydration marker form (`:root` repeated to match two classes).
  const lightSelector = scoped
    ? `[data-palette="${name}"],\n:root${marker(`.xiod-palette-${name}`)}`
    : ":root";
  // Both the palette attribute and the `dark` class land on <html>, so this is
  // one element matching two selectors rather than a descendant relationship.
  const darkSelector = scoped
    ? `.dark[data-palette="${name}"],\n:root:root${marker(`.xiod-dark.xiod-palette-${name}`)}`
    : `.dark,\n:root${marker(".xiod-dark")}`;

  return `${header(name, palette, scoped)}

${lightSelector} {
${declarations(palette.light, { radius: palette.radius })}
}

${darkSelector} {
${declarations(palette.dark)}
}
`;
}

let count = 0;

for (const [name, palette] of Object.entries(PALETTES)) {
  for (const scoped of [false, true]) {
    const file = `${name}${scoped ? ".scoped" : ""}.css`;
    writeFileSync(join(THEMES_DIR, file), render(name, palette, scoped));
    console.log(`  themes/${file}`);
    count += 1;
  }
}

console.log(`✔ Generated ${count} palette stylesheets`);
