/**
 * Palette source of truth.
 *
 * Build-time only — this file is never published. `scripts/build-themes.ts`
 * reads it and generates two stylesheets per palette into `src/themes/`, which
 * holds nothing but generated CSS and is copied wholesale to `dist/themes/`:
 *
 *   <name>.css          `:root` + `.dark` — the plain import, for apps that
 *                       ship one palette. No attribute on `<html>` required.
 *   <name>.scoped.css   `[data-palette="<name>"]` — for apps that let their
 *                       own users switch palettes at runtime via ThemeProvider.
 *
 * The generated files are committed so the published output is reviewable in
 * diffs and so publint can validate the `./themes/*` exports at build time.
 * Edit this file, never the generated CSS.
 *
 * Every palette must define the full token set — the scoped stylesheets are
 * applied on top of an arbitrary other palette, so a missing token would leak
 * the previous palette's value rather than falling back to the neutral base.
 */

/** The complete set of tokens a palette must define. */
export const PALETTE_TOKENS = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "destructive-foreground",
  "info",
  "info-foreground",
  "success",
  "success-foreground",
  "warning",
  "warning-foreground",
  "border",
  "input",
  "ring",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
] as const;

export type PaletteToken = (typeof PALETTE_TOKENS)[number];

/**
 * Which promise a palette makes.
 *
 * `core` palettes are restrained enough to ship to a client without a
 * conversation about it. `expressive` ones trade that neutrality for
 * personality — saturated primaries, loud accents, surfaces with an opinion.
 * Both meet exactly the same contrast thresholds; the split is about intent,
 * not rigour, so that picking a safe palette stays a one-second decision.
 */
export type PaletteFamily = "core" | "expressive";

export interface Palette {
  /** Human-readable name, used in the generated file header. */
  label: string;
  /** One-line description of the palette's character. */
  description: string;
  family: PaletteFamily;
  /** `--radius`, which components consume via `calc(var(--radius) - Npx)`. */
  radius: string;
  light: Record<PaletteToken, string>;
  dark: Record<PaletteToken, string>;
}

/**
 * Two rules every palette below follows, both easy to get backwards when
 * porting a palette written for another design system:
 *
 * 1. A `*-foreground` on `destructive`, `info`, `success` or `warning` is NOT
 *    the text colour for a solid fill. It is a readable shade of the SAME hue
 *    for text on a tint — `bg-destructive/8 text-destructive-foreground`, see
 *    badge.tsx. So it is darker in light mode, lighter in dark mode, and never
 *    white. Components that put text on a solid state fill hardcode
 *    `text-white` instead.
 *
 * 2. Because of that hardcoded `text-white`, `destructive` is squeezed from
 *    both sides in every palette: dark enough for white text (4.5:1) and light
 *    enough to read as a control against the background (3:1, WCAG 1.4.11).
 *
 * `bun scripts/verify-palettes.ts` checks both, plus every text pair.
 */

/** Clay — warm cream and terracotta. */
const clay: Palette = {
  label: "Clay",
  description: "Warm cream and terracotta.",
  family: "core",
  radius: "0.5rem",
  light: {
    background: "#faf9f5",
    foreground: "#3d3929",
    card: "#ffffff",
    "card-foreground": "#3d3929",
    popover: "#ffffff",
    "popover-foreground": "#3d3929",
    primary: "#a9512b",
    "primary-foreground": "#ffffff",
    secondary: "#e9e6dc",
    "secondary-foreground": "#4a4738",
    muted: "#ede9de",
    "muted-foreground": "#6b6858",
    accent: "#e3dfd2",
    "accent-foreground": "#3d3929",
    destructive: "#c0392b",
    "destructive-foreground": "#96271b",
    info: "#2f6f9f",
    "info-foreground": "#1f5378",
    success: "#4a7c4e",
    "success-foreground": "#35603a",
    warning: "#b0741c",
    "warning-foreground": "#875614",
    border: "#dad9d4",
    input: "#cfcdc2",
    ring: "#a9512b",
    sidebar: "#f5f4ee",
    "sidebar-foreground": "#55523f",
    "sidebar-primary": "#a9512b",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e9e6dc",
    "sidebar-accent-foreground": "#3d3929",
    "sidebar-border": "#e2e0d8",
    "sidebar-ring": "#a9512b",
  },
  dark: {
    background: "#262624",
    foreground: "#e8e6df",
    card: "#2d2d2a",
    "card-foreground": "#e8e6df",
    popover: "#30302e",
    "popover-foreground": "#e8e6df",
    primary: "#d97757",
    "primary-foreground": "#2b1a11",
    secondary: "#35342f",
    "secondary-foreground": "#e8e6df",
    muted: "#302f2b",
    "muted-foreground": "#a8a599",
    accent: "#3a3833",
    "accent-foreground": "#e8e6df",
    // Constrained from both sides: button.tsx and badge.tsx hardcode
    // `text-white` on a solid destructive fill, so this must stay dark enough
    // for white text (4.85:1) while staying light enough to read as a control
    // against the background (3.12:1, over the 3:1 floor for non-text UI).
    destructive: "#c9432f",
    "destructive-foreground": "#f2a394",
    info: "#6fa8d0",
    "info-foreground": "#9cc6e4",
    success: "#7fae7c",
    "success-foreground": "#a5c9a2",
    warning: "#d99f4e",
    "warning-foreground": "#e8c188",
    border: "#3e3e38",
    input: "#4a4942",
    ring: "#d97757",
    sidebar: "#1f1e1d",
    "sidebar-foreground": "#b9b6ab",
    "sidebar-primary": "#d97757",
    "sidebar-primary-foreground": "#2b1a11",
    "sidebar-accent": "#2e2d29",
    "sidebar-accent-foreground": "#e8e6df",
    "sidebar-border": "#333230",
    "sidebar-ring": "#d97757",
  },
};

/**
 * Cobalt — deep cobalt blue on cool grey.
 *
 * `info` is pushed to cyan rather than the usual blue. Everywhere else that
 * would be fine, but here a blue `info` reads as the primary, so an
 * informational tint would look like a call to action.
 */
const cobalt: Palette = {
  label: "Cobalt",
  description: "Deep cobalt blue on cool grey.",
  family: "core",
  radius: "0.375rem",
  light: {
    background: "#f7f9fc",
    foreground: "#131a24",
    card: "#ffffff",
    "card-foreground": "#131a24",
    popover: "#ffffff",
    "popover-foreground": "#131a24",
    primary: "#1e4fa8",
    "primary-foreground": "#ffffff",
    secondary: "#dbe6f5",
    "secondary-foreground": "#1c3557",
    muted: "#eef2f8",
    "muted-foreground": "#55607a",
    accent: "#e3ebf7",
    "accent-foreground": "#163055",
    destructive: "#bf3a2e",
    "destructive-foreground": "#97281d",
    info: "#17627d",
    "info-foreground": "#10485c",
    success: "#3f7a52",
    "success-foreground": "#2e5a3c",
    warning: "#a36a12",
    "warning-foreground": "#82540e",
    border: "#dde4ee",
    input: "#c8d3e3",
    ring: "#1e4fa8",
    sidebar: "#f1f5fb",
    "sidebar-foreground": "#3b465c",
    "sidebar-primary": "#1e4fa8",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e2eaf6",
    "sidebar-accent-foreground": "#163055",
    "sidebar-border": "#dde5f0",
    "sidebar-ring": "#1e4fa8",
  },
  dark: {
    background: "#0f1620",
    foreground: "#e4eaf2",
    card: "#16202c",
    "card-foreground": "#e4eaf2",
    popover: "#16202c",
    "popover-foreground": "#e4eaf2",
    primary: "#6ea8e8",
    "primary-foreground": "#0c1a2c",
    secondary: "#1f2e40",
    "secondary-foreground": "#dbe6f5",
    muted: "#182231",
    "muted-foreground": "#93a2b8",
    accent: "#223146",
    "accent-foreground": "#e4eaf2",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#62b4cd",
    "info-foreground": "#93cfe0",
    success: "#7fb184",
    "success-foreground": "#a6ccaa",
    warning: "#d3a24f",
    "warning-foreground": "#e7c68d",
    border: "#24303f",
    input: "#33415a",
    ring: "#6ea8e8",
    sidebar: "#0b111a",
    "sidebar-foreground": "#b3c0d1",
    "sidebar-primary": "#6ea8e8",
    "sidebar-primary-foreground": "#0c1a2c",
    "sidebar-accent": "#151f2c",
    "sidebar-accent-foreground": "#e4eaf2",
    "sidebar-border": "#1b2532",
    "sidebar-ring": "#6ea8e8",
  },
};

/** Iris — indigo and violet on soft lilac. */
const iris: Palette = {
  label: "Iris",
  description: "Indigo and violet on soft lilac.",
  family: "core",
  radius: "0.625rem",
  light: {
    background: "#faf9fd",
    foreground: "#1e1a2e",
    card: "#ffffff",
    "card-foreground": "#1e1a2e",
    popover: "#ffffff",
    "popover-foreground": "#1e1a2e",
    primary: "#5544c4",
    "primary-foreground": "#ffffff",
    secondary: "#e4dffa",
    "secondary-foreground": "#332a63",
    muted: "#f0edf7",
    "muted-foreground": "#5f5878",
    accent: "#ece6fb",
    "accent-foreground": "#2f2559",
    destructive: "#c2323f",
    "destructive-foreground": "#9a2431",
    info: "#2f6482",
    "info-foreground": "#1f4a61",
    success: "#3f7a52",
    "success-foreground": "#2e5a3c",
    warning: "#a36a12",
    "warning-foreground": "#82540e",
    border: "#e6e1f0",
    input: "#d2cae6",
    ring: "#5544c4",
    sidebar: "#f6f3fc",
    "sidebar-foreground": "#453e5e",
    "sidebar-primary": "#5544c4",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#eae4f9",
    "sidebar-accent-foreground": "#2f2559",
    "sidebar-border": "#e8e2f3",
    "sidebar-ring": "#5544c4",
  },
  dark: {
    background: "#14111f",
    foreground: "#ece8f6",
    card: "#1c1829",
    "card-foreground": "#ece8f6",
    popover: "#1c1829",
    "popover-foreground": "#ece8f6",
    primary: "#a596f5",
    "primary-foreground": "#1a1230",
    secondary: "#2a2440",
    "secondary-foreground": "#ece8f6",
    muted: "#1e1a2b",
    "muted-foreground": "#9d95b5",
    accent: "#2f2847",
    "accent-foreground": "#ece8f6",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#74b0d8",
    "info-foreground": "#a0cbe6",
    success: "#7fb184",
    "success-foreground": "#a6ccaa",
    warning: "#d3a24f",
    "warning-foreground": "#e7c68d",
    border: "#2b2540",
    input: "#3a3253",
    ring: "#a596f5",
    sidebar: "#100d18",
    "sidebar-foreground": "#b8b1cc",
    "sidebar-primary": "#a596f5",
    "sidebar-primary-foreground": "#1a1230",
    "sidebar-accent": "#1a1626",
    "sidebar-accent-foreground": "#ece8f6",
    "sidebar-border": "#201b2e",
    "sidebar-ring": "#a596f5",
  },
};

/**
 * Lagoon — deep teal on cool mineral.
 *
 * `success` is pushed to a leafier green than the other palettes use. The
 * shared green sits close enough to a teal primary that a success tint and a
 * primary tint would be hard to tell apart at a glance.
 */
const lagoon: Palette = {
  label: "Lagoon",
  description: "Deep teal on cool mineral.",
  family: "core",
  radius: "0.5rem",
  light: {
    background: "#f5faf9",
    foreground: "#10231f",
    card: "#ffffff",
    "card-foreground": "#10231f",
    popover: "#ffffff",
    "popover-foreground": "#10231f",
    primary: "#0a6b72",
    "primary-foreground": "#ffffff",
    secondary: "#cfe8e2",
    "secondary-foreground": "#14453d",
    muted: "#e9f1ef",
    "muted-foreground": "#4f6360",
    accent: "#dcece8",
    "accent-foreground": "#10352f",
    destructive: "#bb3a2a",
    "destructive-foreground": "#932a1c",
    info: "#2a5fa0",
    "info-foreground": "#1c4577",
    success: "#4a7c3f",
    "success-foreground": "#375c2e",
    warning: "#a36a12",
    "warning-foreground": "#82540e",
    border: "#dbe7e4",
    input: "#c3d5d1",
    ring: "#0a6b72",
    sidebar: "#eef6f4",
    "sidebar-foreground": "#37504b",
    "sidebar-primary": "#0a6b72",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#dfeeea",
    "sidebar-accent-foreground": "#10352f",
    "sidebar-border": "#dcebe7",
    "sidebar-ring": "#0a6b72",
  },
  dark: {
    background: "#0c1614",
    foreground: "#e0eeea",
    card: "#12201d",
    "card-foreground": "#e0eeea",
    popover: "#12201d",
    "popover-foreground": "#e0eeea",
    primary: "#4ac2bd",
    "primary-foreground": "#05201c",
    secondary: "#1e332f",
    "secondary-foreground": "#e0eeea",
    muted: "#142320",
    "muted-foreground": "#8fa39e",
    accent: "#243934",
    "accent-foreground": "#e0eeea",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#74b0d8",
    "info-foreground": "#a0cbe6",
    success: "#8fbe72",
    "success-foreground": "#b0d49a",
    warning: "#d3a24f",
    "warning-foreground": "#e7c68d",
    border: "#1f302c",
    input: "#2e433e",
    ring: "#4ac2bd",
    sidebar: "#081110",
    "sidebar-foreground": "#adc0bb",
    "sidebar-primary": "#4ac2bd",
    "sidebar-primary-foreground": "#05201c",
    "sidebar-accent": "#101d1a",
    "sidebar-accent-foreground": "#e0eeea",
    "sidebar-border": "#182825",
    "sidebar-ring": "#4ac2bd",
  },
};

/** Sepia — aged paper and tanned leather. */
const sepia: Palette = {
  label: "Sepia",
  description: "Aged paper and tanned leather.",
  family: "core",
  radius: "0.25rem",
  light: {
    background: "#f5f1e6",
    foreground: "#4a3f35",
    card: "#fffcf5",
    "card-foreground": "#4a3f35",
    popover: "#fffcf5",
    "popover-foreground": "#4a3f35",
    primary: "#8a6440",
    "primary-foreground": "#ffffff",
    secondary: "#e2d8c3",
    "secondary-foreground": "#4a3f35",
    muted: "#ece5d8",
    "muted-foreground": "#6d5f4c",
    accent: "#d4c8aa",
    "accent-foreground": "#4a3f35",
    destructive: "#a83a28",
    "destructive-foreground": "#8a2e1f",
    info: "#2f6482",
    "info-foreground": "#1f4a61",
    success: "#4a7043",
    "success-foreground": "#365230",
    warning: "#96661a",
    "warning-foreground": "#7a5214",
    border: "#dbd0ba",
    input: "#cbbfa4",
    ring: "#8a6440",
    sidebar: "#ece5d8",
    "sidebar-foreground": "#5c5040",
    "sidebar-primary": "#8a6440",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#ded3b8",
    "sidebar-accent-foreground": "#4a3f35",
    "sidebar-border": "#d8ccb4",
    "sidebar-ring": "#8a6440",
  },
  dark: {
    background: "#2d2621",
    foreground: "#ece5d8",
    card: "#3a322c",
    "card-foreground": "#ece5d8",
    popover: "#3a322c",
    "popover-foreground": "#ece5d8",
    primary: "#c0a080",
    "primary-foreground": "#2d2621",
    secondary: "#4a4039",
    "secondary-foreground": "#ece5d8",
    muted: "#352e28",
    "muted-foreground": "#b3a894",
    accent: "#59493e",
    "accent-foreground": "#ece5d8",
    destructive: "#c9432f",
    "destructive-foreground": "#e8a893",
    info: "#79a8c4",
    "info-foreground": "#a3c6da",
    success: "#86ad7e",
    "success-foreground": "#aac9a4",
    warning: "#d0a052",
    "warning-foreground": "#e3c28c",
    border: "#4a4039",
    input: "#55493f",
    ring: "#c0a080",
    // The original had a near-white #ebebeb here on a dark sidebar — a stock
    // value left over from another palette, which drew a glaring hairline.
    sidebar: "#241e1a",
    "sidebar-foreground": "#c5bcac",
    "sidebar-primary": "#c0a080",
    "sidebar-primary-foreground": "#2d2621",
    "sidebar-accent": "#3a322c",
    "sidebar-accent-foreground": "#ece5d8",
    "sidebar-border": "#3a322c",
    "sidebar-ring": "#c0a080",
  },
};

/** Sage — muted garden green. */
const sage: Palette = {
  label: "Sage",
  description: "Muted garden green.",
  family: "core",
  radius: "0.35rem",
  light: {
    background: "#f8f7f4",
    foreground: "#1f2a24",
    card: "#ffffff",
    "card-foreground": "#1f2a24",
    popover: "#ffffff",
    "popover-foreground": "#1f2a24",
    primary: "#4f6b56",
    "primary-foreground": "#ffffff",
    secondary: "#ced4bf",
    "secondary-foreground": "#35402f",
    muted: "#e8e6e1",
    "muted-foreground": "#566154",
    accent: "#bfc9bb",
    "accent-foreground": "#1f2a24",
    destructive: "#b0342f",
    "destructive-foreground": "#8c2924",
    info: "#2b6480",
    "info-foreground": "#1d4a5f",
    success: "#3f6f45",
    "success-foreground": "#2e5433",
    warning: "#9a6b16",
    "warning-foreground": "#7a5411",
    border: "#e0ded6",
    input: "#cfccc2",
    ring: "#4f6b56",
    sidebar: "#fafaf8",
    "sidebar-foreground": "#3f4a42",
    "sidebar-primary": "#4f6b56",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e3e6dd",
    "sidebar-accent-foreground": "#1f2a24",
    "sidebar-border": "#e2e0d9",
    "sidebar-ring": "#4f6b56",
  },
  // The original dark mode was a generic near-black that happened to carry a
  // green primary. Rebuilt so the surfaces themselves are green-tinted.
  dark: {
    background: "#141815",
    foreground: "#e6ebe6",
    card: "#1b201c",
    "card-foreground": "#e6ebe6",
    popover: "#1b201c",
    "popover-foreground": "#e6ebe6",
    primary: "#8fae94",
    "primary-foreground": "#14201a",
    secondary: "#262d27",
    "secondary-foreground": "#e6ebe6",
    muted: "#222825",
    "muted-foreground": "#9aa89c",
    accent: "#2f3a32",
    "accent-foreground": "#e6ebe6",
    destructive: "#c9432f",
    "destructive-foreground": "#eda392",
    info: "#6fa8c8",
    "info-foreground": "#9cc6dd",
    success: "#7fb184",
    "success-foreground": "#a6ccaa",
    warning: "#cf9c4c",
    "warning-foreground": "#e4c088",
    border: "#2c332e",
    input: "#38403a",
    ring: "#8fae94",
    sidebar: "#101410",
    "sidebar-foreground": "#b5bfb7",
    "sidebar-primary": "#8fae94",
    "sidebar-primary-foreground": "#14201a",
    "sidebar-accent": "#1f2620",
    "sidebar-accent-foreground": "#e6ebe6",
    "sidebar-border": "#232a25",
    "sidebar-ring": "#8fae94",
  },
};

/** Roast — dark coffee and steamed cream. */
const roast: Palette = {
  label: "Roast",
  description: "Dark coffee and steamed cream.",
  family: "core",
  radius: "0.5rem",
  light: {
    background: "#f9f9f9",
    foreground: "#202020",
    card: "#fcfcfc",
    "card-foreground": "#202020",
    popover: "#fcfcfc",
    "popover-foreground": "#202020",
    primary: "#5a4238",
    "primary-foreground": "#ffffff",
    secondary: "#ffdfb5",
    "secondary-foreground": "#582d1d",
    muted: "#efefef",
    "muted-foreground": "#5f5f5f",
    accent: "#e8e8e8",
    "accent-foreground": "#202020",
    destructive: "#b83a1f",
    "destructive-foreground": "#94301a",
    info: "#2f6280",
    "info-foreground": "#204a61",
    success: "#46703f",
    "success-foreground": "#33532e",
    warning: "#96651a",
    "warning-foreground": "#7a5314",
    border: "#d8d8d8",
    input: "#c9c9c9",
    ring: "#5a4238",
    // The original sidebar was stock shadcn grey in light mode and stock zinc
    // in dark — including a blue #1d4ed8 sidebar-primary in a coffee palette.
    // Rebuilt to the palette's own hue in both modes.
    sidebar: "#f4f1ed",
    "sidebar-foreground": "#4a4038",
    "sidebar-primary": "#5a4238",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#ece5dd",
    "sidebar-accent-foreground": "#3a3028",
    "sidebar-border": "#e3ddd5",
    "sidebar-ring": "#5a4238",
  },
  dark: {
    background: "#111111",
    foreground: "#eeeeee",
    card: "#191919",
    "card-foreground": "#eeeeee",
    popover: "#1d1a17",
    "popover-foreground": "#eeeeee",
    primary: "#ffe0c2",
    "primary-foreground": "#2a1c12",
    secondary: "#393028",
    "secondary-foreground": "#ffe0c2",
    muted: "#232323",
    "muted-foreground": "#a8a29b",
    accent: "#2f2822",
    "accent-foreground": "#eeeeee",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#6fa4c6",
    "info-foreground": "#9cc3dc",
    success: "#7fae7c",
    "success-foreground": "#a5c9a2",
    warning: "#d09f52",
    "warning-foreground": "#e5c28d",
    border: "#2a2521",
    input: "#3a332c",
    ring: "#ffe0c2",
    sidebar: "#0d0c0b",
    "sidebar-foreground": "#b8b0a6",
    "sidebar-primary": "#ffe0c2",
    "sidebar-primary-foreground": "#2a1c12",
    "sidebar-accent": "#1c1815",
    "sidebar-accent-foreground": "#eeeeee",
    "sidebar-border": "#211d19",
    "sidebar-ring": "#ffe0c2",
  },
};

/**
 * Crimson — oxblood, olive and steel on gunmetal.
 *
 * Primary is pushed to a deep oxblood rather than the source palette's bright
 * red so it stays clearly distinguishable from `destructive`. A palette whose
 * primary and destructive read as the same colour makes "confirm" and "delete"
 * look alike, which is a usability problem rather than an aesthetic one.
 */
const crimson: Palette = {
  label: "Crimson",
  description: "Oxblood, olive and steel on gunmetal.",
  family: "core",
  radius: "0rem",
  light: {
    background: "#c9c9c7",
    foreground: "#1f1f1f",
    card: "#bcbcba",
    "card-foreground": "#1f1f1f",
    popover: "#bcbcba",
    "popover-foreground": "#1f1f1f",
    primary: "#8f1d1d",
    "primary-foreground": "#ffffff",
    secondary: "#4a5f28",
    "secondary-foreground": "#ffffff",
    muted: "#b8b8b6",
    "muted-foreground": "#454542",
    accent: "#2f5c80",
    "accent-foreground": "#ffffff",
    // The source palette used orange #ff6f00 for destructive, which collided
    // with the warning role. Restored to a red that is still separable from
    // the oxblood primary by lightness.
    destructive: "#a8331f",
    "destructive-foreground": "#7d2415",
    info: "#245a7a",
    "info-foreground": "#17435c",
    success: "#3f6a2a",
    "success-foreground": "#2e4f1f",
    warning: "#8a5a12",
    "warning-foreground": "#6e470e",
    border: "#8f8f8c",
    input: "#8f8f8c",
    ring: "#8f1d1d",
    sidebar: "#bcbcba",
    "sidebar-foreground": "#2a2a28",
    "sidebar-primary": "#8f1d1d",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#a9a9a6",
    "sidebar-accent-foreground": "#1f1f1f",
    "sidebar-border": "#8f8f8c",
    "sidebar-ring": "#8f1d1d",
  },
  dark: {
    background: "#1a1a1a",
    foreground: "#e0e0e0",
    card: "#242424",
    "card-foreground": "#e0e0e0",
    popover: "#242424",
    "popover-foreground": "#e0e0e0",
    primary: "#e65a52",
    "primary-foreground": "#2a0f0e",
    secondary: "#6d9440",
    "secondary-foreground": "#16200c",
    muted: "#232323",
    "muted-foreground": "#a0a09c",
    accent: "#64b5f6",
    "accent-foreground": "#0b1a24",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a08f",
    info: "#74b0d8",
    "info-foreground": "#a0cbe6",
    success: "#86b568",
    "success-foreground": "#aed096",
    warning: "#d2a04e",
    "warning-foreground": "#e6c48b",
    border: "#454545",
    input: "#4f4f4f",
    ring: "#e65a52",
    sidebar: "#141414",
    "sidebar-foreground": "#b5b5b1",
    "sidebar-primary": "#e65a52",
    "sidebar-primary-foreground": "#2a0f0e",
    "sidebar-accent": "#1f1f1f",
    "sidebar-accent-foreground": "#e0e0e0",
    "sidebar-border": "#2b2b2b",
    "sidebar-ring": "#e65a52",
  },
};

/**
 * Sorbet — rose, sky and citrus.
 *
 * A rebuild rather than a port. The source palette ("Candyland") had a pastel
 * pink primary too light to carry text, a pure #ffff00 accent, and a beige
 * muted that clashed with its own pink and blue. The identity — playful,
 * three-colour, high-key — is kept; the values are new.
 */
const sorbet: Palette = {
  label: "Sorbet",
  description: "Rose, sky and citrus.",
  family: "core",
  radius: "0.5rem",
  light: {
    background: "#fdfbfd",
    foreground: "#2b2430",
    card: "#ffffff",
    "card-foreground": "#2b2430",
    popover: "#ffffff",
    "popover-foreground": "#2b2430",
    primary: "#c2306b",
    "primary-foreground": "#ffffff",
    secondary: "#cfe7f5",
    "secondary-foreground": "#1f3d4e",
    muted: "#f1eef4",
    "muted-foreground": "#665c6e",
    accent: "#f7e6b0",
    "accent-foreground": "#4a3d16",
    destructive: "#c22f3a",
    "destructive-foreground": "#98232c",
    info: "#26688f",
    "info-foreground": "#1a4c69",
    success: "#3f7a52",
    "success-foreground": "#2e5a3c",
    warning: "#a36a12",
    "warning-foreground": "#82540e",
    border: "#e7e1ea",
    input: "#d6cede",
    ring: "#c2306b",
    sidebar: "#faf6fb",
    "sidebar-foreground": "#4e4456",
    "sidebar-primary": "#c2306b",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#f2e8f5",
    "sidebar-accent-foreground": "#2b2430",
    "sidebar-border": "#ebe4ee",
    "sidebar-ring": "#c2306b",
  },
  dark: {
    background: "#1a151f",
    foreground: "#f0eaf3",
    card: "#221c28",
    "card-foreground": "#f0eaf3",
    popover: "#221c28",
    "popover-foreground": "#f0eaf3",
    primary: "#f07fae",
    "primary-foreground": "#2a0f1c",
    secondary: "#2a3f4d",
    "secondary-foreground": "#cfe7f5",
    muted: "#251f2b",
    "muted-foreground": "#a89bb0",
    accent: "#4a4326",
    "accent-foreground": "#f7e6b0",
    destructive: "#c9432f",
    "destructive-foreground": "#f2a294",
    info: "#74b0d8",
    "info-foreground": "#a0cbe6",
    success: "#7fb184",
    "success-foreground": "#a6ccaa",
    warning: "#d3a24f",
    "warning-foreground": "#e7c68d",
    border: "#2f2836",
    input: "#3c3344",
    ring: "#f07fae",
    sidebar: "#150f19",
    "sidebar-foreground": "#bdb2c4",
    "sidebar-primary": "#f07fae",
    "sidebar-primary-foreground": "#2a0f1c",
    "sidebar-accent": "#241d2a",
    "sidebar-accent-foreground": "#f0eaf3",
    "sidebar-border": "#2a2330",
    "sidebar-ring": "#f07fae",
  },
};

/* ------------------------------------------------------------------------ *
 * Expressive palettes.
 *
 * These take their cue from animation colour scripts rather than from product
 * design. That is a real difference in kind, not just in loudness: a frame of
 * animation has no body text to keep readable, so its palette is free to run
 * at a chroma no interface can survive.
 *
 * So each one below keeps the *grade* — chroma range, value range, what the
 * shadows are made of, which two hues fight — and spends it where an interface
 * can afford it. The loud colours land on `primary`, `accent`, `ring` and the
 * state roles; `background`, `muted` and `border` stay disciplined, because a
 * saturated surface makes an app unusable no matter how good it looks in a
 * screenshot.
 *
 * Two recurring tricks, both already used by the core palettes:
 *
 *   A colour too light for white text becomes a fill with DARK text instead
 *   (`primary-foreground` is not always white — see Roast).
 *
 *   A colour that collides with a state role gets traded for it rather than
 *   fought: Cathode's phosphor green is not the primary, it IS `success`.
 * ------------------------------------------------------------------------ */

/**
 * Riso — magenta and cyan misprint on newsprint.
 *
 * Offset printing where the plates do not quite line up: two spot inks at full
 * strength, a yellow plate, and paper that was never white. The dark mode is
 * the same inks on press-black rather than a dimmed version of the light one.
 */
const riso: Palette = {
  label: "Riso",
  description: "Magenta and cyan misprint on newsprint.",
  family: "expressive",
  radius: "0rem",
  light: {
    background: "#f6f2e9",
    foreground: "#171310",
    card: "#fffdf6",
    "card-foreground": "#171310",
    popover: "#fffdf6",
    "popover-foreground": "#171310",
    primary: "#e0007f",
    "primary-foreground": "#ffffff",
    secondary: "#bfe6ee",
    "secondary-foreground": "#0a3c47",
    muted: "#ece7db",
    "muted-foreground": "#5c5346",
    // The yellow plate. Loud for a hover surface, which is the point — it is
    // paired with dark text rather than being asked to carry white.
    accent: "#ffe98a",
    "accent-foreground": "#453506",
    destructive: "#c62828",
    "destructive-foreground": "#99201f",
    info: "#0077a8",
    "info-foreground": "#005876",
    success: "#2e7d32",
    "success-foreground": "#226325",
    warning: "#a86a00",
    "warning-foreground": "#855400",
    border: "#ded6c5",
    input: "#c9bfa9",
    ring: "#e0007f",
    sidebar: "#efe9db",
    "sidebar-foreground": "#4a4136",
    "sidebar-primary": "#e0007f",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e4dccb",
    "sidebar-accent-foreground": "#171310",
    "sidebar-border": "#dbd2bf",
    "sidebar-ring": "#e0007f",
  },
  dark: {
    background: "#12100f",
    foreground: "#f2ede2",
    card: "#1b1917",
    "card-foreground": "#f2ede2",
    popover: "#1b1917",
    "popover-foreground": "#f2ede2",
    primary: "#ff4d9d",
    "primary-foreground": "#2b0016",
    secondary: "#123c47",
    "secondary-foreground": "#7fe3f5",
    muted: "#1c1a18",
    "muted-foreground": "#a89e8e",
    accent: "#3d3411",
    "accent-foreground": "#ffe98a",
    destructive: "#c9432f",
    "destructive-foreground": "#f5a08e",
    info: "#4ecde8",
    "info-foreground": "#8fdff0",
    success: "#7fc47f",
    "success-foreground": "#a5d8a5",
    warning: "#ffcc33",
    "warning-foreground": "#ffe08a",
    border: "#2a2724",
    input: "#3a3630",
    ring: "#ff4d9d",
    sidebar: "#0d0b0a",
    "sidebar-foreground": "#bdb3a3",
    "sidebar-primary": "#ff4d9d",
    "sidebar-primary-foreground": "#2b0016",
    "sidebar-accent": "#191614",
    "sidebar-accent-foreground": "#f2ede2",
    "sidebar-border": "#211e1b",
    "sidebar-ring": "#ff4d9d",
  },
};

/**
 * Afterglow — sunset warmth by day, cerulean by night.
 *
 * The one palette that swaps colour temperature between modes rather than just
 * value, because magic hour is precisely that swap: a warm low sun against a
 * sky that has already gone cold. Light mode leads with the sun and keeps the
 * sky on `secondary`; dark mode leads with the sky and keeps the warm horizon
 * on `secondary`. Both temperatures are present in both modes, so the shift
 * reads as the same palette at a different hour rather than as two palettes.
 *
 * Roast sets the precedent for a primary that changes character between modes.
 * `info` is indigo rather than the usual blue so it stays clear of the
 * cerulean, and `destructive` is pushed to crimson so it does not read as a
 * second helping of the sunset primary.
 */
const afterglow: Palette = {
  label: "Afterglow",
  description: "Sunset warmth by day, cerulean by night.",
  family: "expressive",
  radius: "0.75rem",
  light: {
    background: "#f7f6fb",
    foreground: "#1a1a33",
    card: "#ffffff",
    "card-foreground": "#1a1a33",
    popover: "#ffffff",
    "popover-foreground": "#1a1a33",
    primary: "#c93f1c",
    "primary-foreground": "#ffffff",
    secondary: "#cfe4f5",
    "secondary-foreground": "#10405e",
    muted: "#eeedf5",
    "muted-foreground": "#5a5a78",
    accent: "#ffe0ec",
    "accent-foreground": "#7a1f47",
    destructive: "#b81d3f",
    "destructive-foreground": "#8f1630",
    info: "#3d4bb5",
    "info-foreground": "#2b3789",
    success: "#2f7d57",
    "success-foreground": "#235d40",
    warning: "#a86a12",
    "warning-foreground": "#85540e",
    border: "#e4e2ee",
    input: "#cfcce0",
    ring: "#c93f1c",
    sidebar: "#f2f0fa",
    "sidebar-foreground": "#454460",
    "sidebar-primary": "#c93f1c",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e9e6f5",
    "sidebar-accent-foreground": "#1a1a33",
    "sidebar-border": "#e6e3f0",
    "sidebar-ring": "#c93f1c",
  },
  dark: {
    background: "#0d1030",
    foreground: "#e8eafc",
    card: "#151a42",
    "card-foreground": "#e8eafc",
    popover: "#151a42",
    "popover-foreground": "#e8eafc",
    primary: "#4fc3f7",
    "primary-foreground": "#04243a",
    // The warm horizon under a cold sky — the one place the palette is allowed
    // to go warm, which is what makes the cyan read as light rather than paint.
    secondary: "#4a2436",
    "secondary-foreground": "#ffc9a8",
    muted: "#141834",
    "muted-foreground": "#9ba0c8",
    accent: "#2a2a5e",
    "accent-foreground": "#e8eafc",
    destructive: "#c9432f",
    "destructive-foreground": "#f2a08d",
    info: "#7f8cff",
    "info-foreground": "#a8b2ff",
    success: "#6fcf97",
    "success-foreground": "#9be0b5",
    warning: "#ffb74d",
    "warning-foreground": "#ffd08a",
    border: "#262b55",
    input: "#343a6e",
    ring: "#4fc3f7",
    sidebar: "#090b26",
    "sidebar-foreground": "#b6bbdd",
    "sidebar-primary": "#4fc3f7",
    "sidebar-primary-foreground": "#04243a",
    "sidebar-accent": "#12163a",
    "sidebar-accent-foreground": "#e8eafc",
    "sidebar-border": "#1b1f47",
    "sidebar-ring": "#4fc3f7",
  },
};

/**
 * Cathode — hot magenta and phosphor green on cold concrete.
 *
 * Nineties animation techno-noir: limited inks, heavy blacks, neon doing all
 * the work.
 * `success` is the phosphor green rather than the usual leaf green — the
 * colour was going to fight whatever occupied that role, so it took the role
 * instead. Surfaces are deliberately colder and greyer than Riso's warm paper,
 * which is what keeps two magenta-forward palettes from reading as one.
 */
const cathode: Palette = {
  label: "Cathode",
  description: "Hot magenta and phosphor green on cold concrete.",
  family: "expressive",
  radius: "0.125rem",
  light: {
    background: "#eaecec",
    foreground: "#101314",
    card: "#f5f7f7",
    "card-foreground": "#101314",
    popover: "#f5f7f7",
    "popover-foreground": "#101314",
    primary: "#ab0f7d",
    "primary-foreground": "#ffffff",
    secondary: "#d3dadb",
    "secondary-foreground": "#1b2628",
    muted: "#e2e6e6",
    "muted-foreground": "#515a5b",
    accent: "#d6e8ec",
    "accent-foreground": "#0d3a45",
    destructive: "#c22020",
    "destructive-foreground": "#991919",
    info: "#16607f",
    "info-foreground": "#0f4459",
    success: "#3f8f1f",
    "success-foreground": "#2f6b17",
    warning: "#9c6600",
    "warning-foreground": "#7d5100",
    border: "#d5dada",
    input: "#bfc6c6",
    ring: "#ab0f7d",
    sidebar: "#e4e8e8",
    "sidebar-foreground": "#3c4445",
    "sidebar-primary": "#ab0f7d",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#d8dede",
    "sidebar-accent-foreground": "#101314",
    "sidebar-border": "#d1d7d7",
    "sidebar-ring": "#ab0f7d",
  },
  dark: {
    background: "#0b0e0f",
    foreground: "#dfe6e7",
    card: "#141819",
    "card-foreground": "#dfe6e7",
    popover: "#141819",
    "popover-foreground": "#dfe6e7",
    primary: "#f81ad0",
    "primary-foreground": "#2b0019",
    secondary: "#1b2426",
    "secondary-foreground": "#dfe6e7",
    muted: "#14191a",
    "muted-foreground": "#93a0a1",
    accent: "#10333c",
    "accent-foreground": "#5fe0f5",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#4dd0e1",
    "info-foreground": "#8ae0ec",
    success: "#7cff50",
    "success-foreground": "#a8ff8a",
    warning: "#ffb300",
    "warning-foreground": "#ffd166",
    border: "#212829",
    input: "#303839",
    ring: "#f81ad0",
    sidebar: "#070a0a",
    "sidebar-foreground": "#b0babb",
    "sidebar-primary": "#f81ad0",
    "sidebar-primary-foreground": "#2b0019",
    "sidebar-accent": "#121718",
    "sidebar-accent-foreground": "#dfe6e7",
    "sidebar-border": "#1a2021",
    "sidebar-ring": "#f81ad0",
  },
};

/**
 * Ion — violet and readout green on instrument grey.
 *
 * The mecha-cockpit pairing: a saturated violet against a signal green, on
 * surfaces cold enough to read as equipment. `success` and `secondary` both
 * draw on the green so it reads as instrumentation rather than decoration.
 */
const ion: Palette = {
  label: "Ion",
  description: "Violet and readout green on instrument grey.",
  family: "expressive",
  radius: "0rem",
  light: {
    background: "#f4f3f7",
    foreground: "#17141f",
    card: "#fbfafd",
    "card-foreground": "#17141f",
    popover: "#fbfafd",
    "popover-foreground": "#17141f",
    primary: "#5b2d8e",
    "primary-foreground": "#ffffff",
    secondary: "#cfe3b8",
    "secondary-foreground": "#2d4416",
    muted: "#eae8ef",
    "muted-foreground": "#58526a",
    accent: "#dfd6ec",
    "accent-foreground": "#35205a",
    destructive: "#c1272d",
    "destructive-foreground": "#971e23",
    info: "#1f5f8b",
    "info-foreground": "#164561",
    success: "#4a7a1f",
    "success-foreground": "#375c17",
    warning: "#a06400",
    "warning-foreground": "#7f4f00",
    border: "#e2dfe9",
    input: "#cec8dc",
    ring: "#5b2d8e",
    sidebar: "#efedf4",
    "sidebar-foreground": "#423c52",
    "sidebar-primary": "#5b2d8e",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e5e0ee",
    "sidebar-accent-foreground": "#17141f",
    "sidebar-border": "#e3dfec",
    "sidebar-ring": "#5b2d8e",
  },
  dark: {
    background: "#100c18",
    foreground: "#e9e4f2",
    card: "#191322",
    "card-foreground": "#e9e4f2",
    popover: "#191322",
    "popover-foreground": "#e9e4f2",
    primary: "#b45cff",
    "primary-foreground": "#1c0733",
    secondary: "#2a3d1c",
    "secondary-foreground": "#c9e8a8",
    muted: "#171122",
    "muted-foreground": "#9a92ad",
    accent: "#2a1d40",
    "accent-foreground": "#e9e4f2",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#6fa8ff",
    "info-foreground": "#9ec3ff",
    success: "#8fd94f",
    "success-foreground": "#b3e585",
    warning: "#ffb020",
    "warning-foreground": "#ffcd70",
    border: "#262034",
    input: "#363048",
    ring: "#b45cff",
    sidebar: "#0b0812",
    "sidebar-foreground": "#b6aecb",
    "sidebar-primary": "#b45cff",
    "sidebar-primary-foreground": "#1c0733",
    "sidebar-accent": "#150f1f",
    "sidebar-accent-foreground": "#e9e4f2",
    "sidebar-border": "#1d1729",
    "sidebar-ring": "#b45cff",
  },
};

/**
 * Cel — sky blue and marigold, flat and high-key.
 *
 * Broadcast-cartoon flatness: bright, cheerful, no gradients implied. Marigold
 * is the memorable colour, so it takes `primary` — too light for white text,
 * but `default` buttons use `primary-foreground`, so it becomes a fill with
 * dark text (the Roast trick). The sky blue moves to `secondary` and to `ring`,
 * where marigold could not reach 3:1 against the near-white background. `info`
 * is teal to stay clear of that blue.
 *
 * Marigold rather than the blue because the blue family is the crowded one —
 * a sky-blue `primary` sat 0.027 from Cobalt in OKLab, close enough to read as
 * the same palette.
 */
const cel: Palette = {
  label: "Cel",
  description: "Sky blue and marigold, flat and high-key.",
  family: "expressive",
  radius: "1rem",
  light: {
    background: "#fdfcf7",
    foreground: "#1f2430",
    card: "#ffffff",
    "card-foreground": "#1f2430",
    popover: "#ffffff",
    "popover-foreground": "#1f2430",
    primary: "#ffc72c",
    "primary-foreground": "#4a3800",
    secondary: "#cfe4f5",
    "secondary-foreground": "#14507f",
    muted: "#f2f0e8",
    "muted-foreground": "#5b6070",
    accent: "#e3f0fa",
    "accent-foreground": "#14507f",
    destructive: "#d32f2f",
    "destructive-foreground": "#a52424",
    info: "#0e7c8c",
    "info-foreground": "#0a5c68",
    success: "#2e8b3d",
    "success-foreground": "#226a2e",
    // Pushed to burnt amber so the warning tint reads as a state rather than
    // as a wash of `primary`.
    warning: "#a85f00",
    "warning-foreground": "#7a4400",
    border: "#e9e6db",
    input: "#d5d1c2",
    ring: "#1a72bd",
    sidebar: "#fbf8ee",
    "sidebar-foreground": "#4a4f5c",
    "sidebar-primary": "#ffc72c",
    "sidebar-primary-foreground": "#4a3800",
    "sidebar-accent": "#dceaf7",
    "sidebar-accent-foreground": "#14507f",
    "sidebar-border": "#eee9d9",
    "sidebar-ring": "#1a72bd",
  },
  dark: {
    background: "#131722",
    foreground: "#eef1f7",
    card: "#1b2130",
    "card-foreground": "#eef1f7",
    popover: "#1b2130",
    "popover-foreground": "#eef1f7",
    primary: "#ffd93d",
    "primary-foreground": "#4a3800",
    secondary: "#1e3d57",
    "secondary-foreground": "#a8d8ff",
    muted: "#191f2b",
    "muted-foreground": "#99a2b5",
    accent: "#2a3346",
    "accent-foreground": "#eef1f7",
    destructive: "#c9432f",
    "destructive-foreground": "#f0a48f",
    info: "#4fd0e0",
    "info-foreground": "#8ce0eb",
    success: "#6fd47f",
    "success-foreground": "#9ce3a8",
    warning: "#f0932b",
    "warning-foreground": "#f7b877",
    border: "#262e3e",
    input: "#354054",
    ring: "#4fa8e8",
    sidebar: "#0f131c",
    "sidebar-foreground": "#b4bccb",
    "sidebar-primary": "#ffd93d",
    "sidebar-primary-foreground": "#4a3800",
    "sidebar-accent": "#171d28",
    "sidebar-accent-foreground": "#eef1f7",
    "sidebar-border": "#1e2532",
    "sidebar-ring": "#4fa8e8",
  },
};

/**
 * Taffy — watermelon, sky and lemon.
 *
 * Cute at full chroma: three candy colours that in an illustration would sit
 * at pastel weight and here have to be deepened until they carry text. The
 * pastel versions survive as `secondary` and `accent`, which never do.
 *
 * The primary is watermelon rather than bubblegum because the pink end of the
 * spectrum already holds Riso, Sorbet, Cathode and Mochi; a fifth pink was
 * indistinguishable from Riso in light mode.
 */
const taffy: Palette = {
  label: "Taffy",
  description: "Watermelon, sky and lemon.",
  family: "expressive",
  radius: "1.25rem",
  light: {
    background: "#fff7fb",
    foreground: "#3d1f30",
    card: "#ffffff",
    "card-foreground": "#3d1f30",
    popover: "#ffffff",
    "popover-foreground": "#3d1f30",
    primary: "#e01e3c",
    "primary-foreground": "#ffffff",
    secondary: "#bfe9ff",
    "secondary-foreground": "#0d3f5c",
    muted: "#fdeef5",
    "muted-foreground": "#6d5060",
    accent: "#fff0a8",
    "accent-foreground": "#5c4a00",
    destructive: "#a8173a",
    "destructive-foreground": "#85122d",
    info: "#1f7fb5",
    "info-foreground": "#155e87",
    success: "#2e8b57",
    "success-foreground": "#226a42",
    warning: "#b5730a",
    "warning-foreground": "#8f5a08",
    border: "#fbe0ec",
    input: "#f2c7dc",
    ring: "#e01e3c",
    sidebar: "#fff2f8",
    "sidebar-foreground": "#5c3b4c",
    "sidebar-primary": "#e01e3c",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#ffe6f1",
    "sidebar-accent-foreground": "#3d1f30",
    "sidebar-border": "#fae2ee",
    "sidebar-ring": "#e01e3c",
  },
  dark: {
    background: "#24121c",
    foreground: "#ffe9f3",
    card: "#2e1826",
    "card-foreground": "#ffe9f3",
    popover: "#2e1826",
    "popover-foreground": "#ffe9f3",
    primary: "#fb5f80",
    "primary-foreground": "#3d0022",
    secondary: "#143a4d",
    "secondary-foreground": "#a8e4ff",
    muted: "#2a1521",
    "muted-foreground": "#c9a3b6",
    accent: "#4a3d0f",
    "accent-foreground": "#ffef9e",
    destructive: "#c9432f",
    "destructive-foreground": "#f7a794",
    info: "#7fd0ff",
    "info-foreground": "#a8e0ff",
    success: "#7fd9a8",
    "success-foreground": "#a5e6c4",
    warning: "#ffc94d",
    "warning-foreground": "#ffde91",
    border: "#3d2130",
    input: "#4d2b3d",
    ring: "#fb5f80",
    sidebar: "#1c0d16",
    "sidebar-foreground": "#d1b2c0",
    "sidebar-primary": "#fb5f80",
    "sidebar-primary-foreground": "#3d0022",
    "sidebar-accent": "#2a1420",
    "sidebar-accent-foreground": "#ffe9f3",
    "sidebar-border": "#2e1826",
    "sidebar-ring": "#fb5f80",
  },
};

/**
 * Mochi — milky orchid, mint and blush.
 *
 * The soft half of cute, where Taffy is the loud half. Orchid rather than pink
 * for the primary, which keeps it clear of both Taffy's watermelon and Iris's
 * violet, and lets the mint and blush stay genuinely pale.
 */
const mochi: Palette = {
  label: "Mochi",
  description: "Milky orchid, mint and blush.",
  family: "expressive",
  radius: "1.5rem",
  light: {
    background: "#fbf9fd",
    foreground: "#3a3348",
    card: "#ffffff",
    "card-foreground": "#3a3348",
    popover: "#ffffff",
    "popover-foreground": "#3a3348",
    primary: "#a04d92",
    "primary-foreground": "#ffffff",
    secondary: "#cdf0e0",
    "secondary-foreground": "#14513a",
    muted: "#f4f1f7",
    "muted-foreground": "#625a70",
    accent: "#ffe4ec",
    "accent-foreground": "#7d2f4a",
    destructive: "#c33a4e",
    "destructive-foreground": "#9a2b3c",
    info: "#3a6fa8",
    "info-foreground": "#29527d",
    success: "#2f7d57",
    "success-foreground": "#235d40",
    warning: "#a8700f",
    "warning-foreground": "#85580c",
    border: "#ece7f0",
    input: "#dbd3e2",
    ring: "#a04d92",
    sidebar: "#f8f5fa",
    "sidebar-foreground": "#4f4760",
    "sidebar-primary": "#a04d92",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#f2e8f2",
    "sidebar-accent-foreground": "#3a3348",
    "sidebar-border": "#ebe5ee",
    "sidebar-ring": "#a04d92",
  },
  dark: {
    background: "#1c1824",
    foreground: "#efe9f5",
    card: "#251f2e",
    "card-foreground": "#efe9f5",
    popover: "#251f2e",
    "popover-foreground": "#efe9f5",
    primary: "#e4a0d8",
    "primary-foreground": "#2e0f28",
    secondary: "#1a3d31",
    "secondary-foreground": "#a8e8cd",
    muted: "#211c2a",
    "muted-foreground": "#a89fb5",
    accent: "#3d2430",
    "accent-foreground": "#ffd0dd",
    destructive: "#c9432f",
    "destructive-foreground": "#f2a493",
    info: "#8fb8e8",
    "info-foreground": "#b3cef0",
    success: "#8fdcb5",
    "success-foreground": "#b0e8ca",
    warning: "#e8c470",
    "warning-foreground": "#f0d79c",
    border: "#2e2838",
    input: "#3d3548",
    ring: "#e4a0d8",
    sidebar: "#16121d",
    "sidebar-foreground": "#bdb4c9",
    "sidebar-primary": "#e4a0d8",
    "sidebar-primary-foreground": "#2e0f28",
    "sidebar-accent": "#1f1a27",
    "sidebar-accent-foreground": "#efe9f5",
    "sidebar-border": "#262030",
    "sidebar-ring": "#e4a0d8",
  },
};

/**
 * Toxin — biohazard green and blood on wet concrete.
 *
 * Survival-horror: sickly green as the signal colour, arterial red for
 * anything that hurts, everything else damp grey. `success` is pushed to teal
 * rather than green — the usual green would be indistinguishable from the
 * primary, and here that would mean "safe" and "contaminated" look alike.
 */
const toxin: Palette = {
  label: "Toxin",
  description: "Biohazard green and blood on wet concrete.",
  family: "expressive",
  radius: "0.125rem",
  light: {
    background: "#e8eae6",
    foreground: "#16180f",
    card: "#f2f4ef",
    "card-foreground": "#16180f",
    popover: "#f2f4ef",
    "popover-foreground": "#16180f",
    primary: "#4a6b1f",
    "primary-foreground": "#ffffff",
    secondary: "#d2d6cc",
    "secondary-foreground": "#232619",
    muted: "#dfe2db",
    "muted-foreground": "#4f5548",
    accent: "#cfd9b8",
    "accent-foreground": "#2b3a12",
    destructive: "#a51818",
    "destructive-foreground": "#821313",
    info: "#1f5f7d",
    "info-foreground": "#154458",
    success: "#17705e",
    "success-foreground": "#115345",
    warning: "#8a6000",
    "warning-foreground": "#6e4c00",
    border: "#d3d7cd",
    input: "#bcc2b4",
    ring: "#4a6b1f",
    sidebar: "#e0e3dc",
    "sidebar-foreground": "#3a4033",
    "sidebar-primary": "#4a6b1f",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#d5dac9",
    "sidebar-accent-foreground": "#16180f",
    "sidebar-border": "#cdd2c6",
    "sidebar-ring": "#4a6b1f",
  },
  dark: {
    background: "#0e100c",
    foreground: "#dfe3d8",
    card: "#171a13",
    "card-foreground": "#dfe3d8",
    popover: "#171a13",
    "popover-foreground": "#dfe3d8",
    primary: "#9fd42f",
    "primary-foreground": "#17200a",
    secondary: "#232a1c",
    "secondary-foreground": "#dfe3d8",
    muted: "#14170f",
    "muted-foreground": "#98a08c",
    accent: "#2b3a12",
    "accent-foreground": "#cfe89a",
    destructive: "#d32f2f",
    "destructive-foreground": "#f09b9b",
    info: "#6fb0d0",
    "info-foreground": "#9cc9e0",
    success: "#4fc9a8",
    "success-foreground": "#85dcc2",
    warning: "#d9a838",
    "warning-foreground": "#ecc880",
    border: "#232619",
    input: "#333a26",
    ring: "#9fd42f",
    sidebar: "#0a0c08",
    "sidebar-foreground": "#b0b8a4",
    "sidebar-primary": "#9fd42f",
    "sidebar-primary-foreground": "#17200a",
    "sidebar-accent": "#141710",
    "sidebar-accent-foreground": "#dfe3d8",
    "sidebar-border": "#1c2016",
    "sidebar-ring": "#9fd42f",
  },
};

/**
 * Cinder — molten orange on cold ash.
 *
 * `destructive` is crimson rather than the usual red-orange, which against a
 * molten primary would read as more of the same colour instead of as danger.
 * The light mode is ash rather than paper — cool mineral grey — so the ember
 * stays the only warm thing on the page in either mode.
 */
const cinder: Palette = {
  label: "Cinder",
  description: "Molten orange on cold ash.",
  family: "expressive",
  radius: "0.25rem",
  light: {
    background: "#edecea",
    foreground: "#1a1714",
    card: "#f7f6f4",
    "card-foreground": "#1a1714",
    popover: "#f7f6f4",
    "popover-foreground": "#1a1714",
    primary: "#9e3608",
    "primary-foreground": "#ffffff",
    secondary: "#dcd8d2",
    "secondary-foreground": "#2b2621",
    muted: "#e4e2df",
    "muted-foreground": "#565049",
    accent: "#f2ded0",
    "accent-foreground": "#5c3218",
    destructive: "#9e1b2e",
    "destructive-foreground": "#7c1424",
    info: "#1f5f8b",
    "info-foreground": "#164561",
    success: "#3f7040",
    "success-foreground": "#2e532f",
    warning: "#96601a",
    "warning-foreground": "#784c14",
    border: "#dcd9d5",
    input: "#c6c2bc",
    ring: "#9e3608",
    sidebar: "#e6e4e1",
    "sidebar-foreground": "#3f3a34",
    "sidebar-primary": "#9e3608",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#ddd8d2",
    "sidebar-accent-foreground": "#1a1714",
    "sidebar-border": "#d7d3ce",
    "sidebar-ring": "#9e3608",
  },
  dark: {
    background: "#14100e",
    foreground: "#ede7e0",
    card: "#1e1815",
    "card-foreground": "#ede7e0",
    popover: "#1e1815",
    "popover-foreground": "#ede7e0",
    primary: "#ff6b1f",
    "primary-foreground": "#2b0d00",
    secondary: "#2e241e",
    "secondary-foreground": "#ede7e0",
    muted: "#1a1613",
    "muted-foreground": "#a89a8e",
    accent: "#3d2415",
    "accent-foreground": "#ffb98a",
    destructive: "#d92b4a",
    "destructive-foreground": "#ff9aad",
    info: "#6fa8d0",
    "info-foreground": "#9cc6e4",
    success: "#7fae7c",
    "success-foreground": "#a5c9a2",
    warning: "#ffb020",
    "warning-foreground": "#ffcd70",
    border: "#2a231e",
    input: "#3a312a",
    ring: "#ff6b1f",
    sidebar: "#0f0c0a",
    "sidebar-foreground": "#b8ada2",
    "sidebar-primary": "#ff6b1f",
    "sidebar-primary-foreground": "#2b0d00",
    "sidebar-accent": "#1a1512",
    "sidebar-accent-foreground": "#ede7e0",
    "sidebar-border": "#221c18",
    "sidebar-ring": "#ff6b1f",
  },
};

/**
 * Blacklight — ultraviolet, acid green and hot pink.
 *
 * The one that should not work: three colours that fluoresce under UV, none of
 * which belongs in the same room as the others, on a violet-black that is not
 * quite black. It holds together because the surfaces do all the restraining,
 * and because the three loud colours are kept in separate roles — primary,
 * secondary, accent — so they never sit adjacent at full strength.
 */
const blacklight: Palette = {
  label: "Blacklight",
  description: "Ultraviolet, acid green and hot pink.",
  family: "expressive",
  radius: "0.75rem",
  light: {
    background: "#f7f3ff",
    foreground: "#1f1233",
    card: "#fdfbff",
    "card-foreground": "#1f1233",
    popover: "#fdfbff",
    "popover-foreground": "#1f1233",
    primary: "#7b16d6",
    "primary-foreground": "#ffffff",
    secondary: "#d9ffb0",
    "secondary-foreground": "#2e4a05",
    muted: "#f0eaf9",
    "muted-foreground": "#5f5178",
    accent: "#ffd6f5",
    "accent-foreground": "#78156a",
    destructive: "#c4204f",
    "destructive-foreground": "#9a1a3e",
    info: "#4a3fc4",
    "info-foreground": "#342c94",
    success: "#3f7a2e",
    "success-foreground": "#2e5a22",
    warning: "#9c6a0a",
    "warning-foreground": "#7d5408",
    border: "#e8dff5",
    input: "#d5c7e8",
    ring: "#7b16d6",
    sidebar: "#f3edfc",
    "sidebar-foreground": "#453a5c",
    "sidebar-primary": "#7b16d6",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#ece2f8",
    "sidebar-accent-foreground": "#1f1233",
    "sidebar-border": "#e9e0f6",
    "sidebar-ring": "#7b16d6",
  },
  dark: {
    background: "#0d0418",
    foreground: "#f0e4ff",
    card: "#170a26",
    "card-foreground": "#f0e4ff",
    popover: "#170a26",
    "popover-foreground": "#f0e4ff",
    primary: "#e05aff",
    "primary-foreground": "#22003d",
    secondary: "#1f3d0a",
    "secondary-foreground": "#c4ff70",
    muted: "#150a20",
    "muted-foreground": "#a893bd",
    accent: "#3d0a35",
    "accent-foreground": "#ff9ae8",
    destructive: "#d92b4a",
    "destructive-foreground": "#ff9aad",
    info: "#7f8cff",
    "info-foreground": "#a8b2ff",
    success: "#8fff5c",
    "success-foreground": "#b5ff94",
    warning: "#ffcc33",
    "warning-foreground": "#ffe08a",
    border: "#26113a",
    input: "#35194f",
    ring: "#e05aff",
    sidebar: "#08020f",
    "sidebar-foreground": "#bda8cf",
    "sidebar-primary": "#e05aff",
    "sidebar-primary-foreground": "#22003d",
    "sidebar-accent": "#130820",
    "sidebar-accent-foreground": "#f0e4ff",
    "sidebar-border": "#1c0d2b",
    "sidebar-ring": "#e05aff",
  },
};

export const PALETTES: Record<string, Palette> = {
  afterglow,
  blacklight,
  cathode,
  riso,
  cel,
  cinder,
  ion,
  mochi,
  taffy,
  toxin,
  clay,
  cobalt,
  crimson,
  iris,
  lagoon,
  roast,
  sage,
  sepia,
  sorbet,
};
